FeatureData$Nuc.Aspect.Ratio <- NULL
FeatureData$Nuc.Aspect.Ratio.Intensity <- NULL
FeatureData$Nuc.Circularity <- NULL
FeatureData$Nuc.Compactness <- NULL
FeatureData$Nuc.Elongatedness <- NULL
FeatureData$Nuc.Lobe.Count <- NULL
FeatureData$Nuc.Shape.Ratio <- NULL
FeatureData$Nuc.Symmetry.2 <- NULL
FeatureData$Nuc.Symmetry.3 <- NULL
FeatureData$Nuc.Symmetry.4 <- NULL

FeatureData$Cell.Aspect.Ratio <- NULL
FeatureData$Cell.Aspect.Ratio.Intensity <- NULL
FeatureData$Cell.Circularity <- NULL
FeatureData$Cell.Compactness <- NULL
FeatureData$Cell.Elongatedness <- NULL
FeatureData$Cell.Lobe.Count <- NULL
FeatureData$Cell.Shape.Ratio <- NULL
FeatureData$Cell.Symmetry.2 <- NULL
FeatureData$Cell.Symmetry.3 <- NULL
FeatureData$Cell.Symmetry.4 <- NULL